Trovi 2.0: Wire Auth to Existing Endpoints
ChameleonCloud/trovi pull request #21
Opened 2022-02-15 19:45 UTC by super-cooper

Trovi 2.0: Wire Auth to Existing Endpoints

Adds authentication to existing Trovi API endpoints. All endpoints follow the same authentication scheme, which is simply validating a Trovi token passed via the `access_token` query parameter. The token is then used by the endpoints and `Permission` classes to perform authorization. This can be "bypassed" for specific Artifacts by providing the Artifact's `sharing_key` as a different query parameter.

Some authentication code is moved to the `trovi.common` package, as it was decoupled from the `auth` app itself. It makes more sense to put it here, as it is relevant to the entire project and not just token exchange.

New authentication code includes the `TroviTokenAuthentication` class, which extracts and validates trovi tokens from the request URL, and then attaches them to the `Request` object in the form of a `JWT` object.

Once the token is extracted, authorization is performed via several classes in the `trovi.common.permissions` module. `*ScopedPermissions` classes determine if the scope delegated to the incoming token permits the user to perform their requested operation on the requested resource. There are also the `*VisibilityPermission` classes, which determine if the user has permission to view the requested resource.

The code in `ListArtifactsOrderingFilter` is modified to only show artifacts that the user has permission to view. A small bug with the default ordering, which was backwards, is also fixed.

`TokenGrantRequest` serializer now follows the expected object-creation flow of a Django REST Framework serializer, which means validation is performed properly.

We now make use of `owner_urn` fields to determine if a user has permission to perform certain operations on Artifacts. Right now, it only prevents modification of the `owner_urn` field. This work unfortunately has to be done in the serializer, to avoid having redundant parsing in a `Permission` class.

* ✅ Refactor existing tests to properly authenticate
* ♲ Refactor auth providers to be a little more generalized
* 🐛 Fix a regex bug with token schema
* 🐛 Fix a caching bug with the timed cache decorator. Confirmed it worked by adding a log message to the signing key refresh function.
* 📢 Introduce a new `InvalidToken` exception
* 🦋 Migrate Artifact table to not supply a default `owner_urn`. This is now resolved via the Artifact creator's auth token.
* ➖ Remove dependency on `djangorestframework-simplejwt`
    * We weren't using it for much
    * Its token exchange view was using DRF serializers incorrectly
    * Its `InvalidToken` exception was raising 401 errors instead of 403

2022-02-15 19:49 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Trovi 2.0: Wire Auth to Existing Endpoints](https://trello.com/c/6ZvXXGna/2574-trovi-20-wire-auth-to-existing-endpoints)

2022-02-15 20:37 UTC, super-cooper commented
It seems there is an issue with the https://github.com/reviewdog/action-black runner. Opening this for review nonetheless.

2022-03-03 21:03 UTC, diurnalist commented on trovi/auth/schema.py
> +                "pattern": r"^\s*[A-Za-z0-9:-_]+(?:\s+[A-Za-z0-9:-_]+)*\s*$",
Printable regex ascii characters are 0x20 - 0x7E. 0x20 is the space character. ASCII chars are allowed in scopes.

So this can be just

```
# space-delimited ascii char sequence
r"^([\x21-\x7E]+\x20?)+$"
```

no? It will potentially have a trailing space, but the original regex has this behavior too.

2022-03-03 21:10 UTC, diurnalist commented on trovi/auth/serializers.py
> +        requested_scope = validated_data.get("scope", [JWT.Scopes.ARTIFACTS_READ])
Why is the default needed here? I worry about the two defaults getting out of sync at some point.

2022-03-03 21:11 UTC, diurnalist commented on trovi/auth/serializers.py
> +        return trovi_token
The above TODO feels quite important - how much more work is it?

2022-03-03 21:16 UTC, diurnalist commented on trovi/common/authenticators.py
> +        access_token = request.query_params.get("access_token")
I made a comment on another pull request to this effect, but really we should be looking in the headers for this token. Standard practice is to have a header like:

```
Authorization: Bearer <token>
```

2022-03-03 21:23 UTC, diurnalist commented on trovi/common/authenticators.py
> +            return None
This is not a tuple, it will break anything expecting a tuple on the return.

2022-03-03 21:29 UTC, diurnalist commented on trovi/common/permissions.py
> +            "UPDATE": {JWT.Scopes.ARTIFACTS_WRITE, JWT.Scopes.ARTIFACTS_READ},
Why does UPDATE and PATCH require both read and write? I guess semantically it makes sense, never really considered this level of specificity before

2022-03-03 21:29 UTC, diurnalist commented on trovi/common/permissions.py
> +    TODO allow owners to specify writability for their Artifacts
What does this TODO mean? writability?

2022-03-03 21:31 UTC, diurnalist commented on trovi/common/permissions.py
> +        if not obj.authors.filter(email__iexact=user).exists():
"authors" is just metadata saying who should get credit. It should not be used for authorization. Only the owner should be used here, I think.

2022-03-03 21:34 UTC, diurnalist commented on trovi/common/permissions.py
> +        if not obj.authors.filter(email__iexact=user).exists():
I'm quite confused by this logic, but it would be b/c I don't get DRF permissions. has_object_permission means the request has permission to do... something on the object. Permission to do what, precisely? How do we know?

Also, important for REALLY important auth code to be as clear as possible. I think some additional vars might help:

```python
is_owner = do_some_owner_check(obj.owner, token.uid)
if is_owner:
    # Owner can do anything?
    return True
else:
    return False
```

2022-03-03 21:37 UTC, diurnalist commented on trovi/common/permissions.py
> +                return obj.authors.filter(email__iexact=user).exists()
Same as above, we can't use authors for authorization. At least, that's not how the previous system worked, and I think it's very important to separate artifact management roles from artifact authors. The former is delegation, the latter is documentation.

2022-03-03 21:37 UTC, diurnalist commented on trovi/common/permissions.py
> +            return True
I think this should come first as an early return, in general in my view it's stylistically a code smell to have very unequal (or long) branching in a conditional.

```python
if obj.visibility == Artifact.Visibility.PUBLIC:
    return True
```

2022-03-03 21:39 UTC, diurnalist commented on trovi/common/permissions.py
> +        return super(ArtifactVersionVisibilityPermission, self).has_object_permission(
Does the niche use-case of the polymorphic overload justify the additional length and possibility of messing up the first arg for super() here?

2022-03-03 21:45 UTC, diurnalist commented on trovi/common/permissions.py
> +        return super(ArtifactVersionScopedPermission, self).has_object_permission(
It's a bit odd that this extends the base class but it has to call it on a slightly different input (going in to the "artifact" relation.)

Expressing this as composition makes this a bit more clear:

```python
class ArtifactVersionScopedPermission(permissions.BasePermission):
    artifact_scoped_permission = ArtifactScopedPermission()

    def has_permission(self, request: Request, view: views.View, obj: ArtifactVersion) -> bool:
        return self.artifact_scoped_permission.has_object_permission(request, view, obj.artifact)
```

2022-03-03 21:47 UTC, diurnalist commented on trovi/common/permissions.py
> +        return token and token.iss == settings.TROVI_FQDN
Doesn't seem like this should have to check the issuer. Checking the issuer implies that we allow JWTs NOT issued by Trovi this far in the code, which probably shouldn't be the case.

Maybe you can just utilize https://www.django-rest-framework.org/api-guide/permissions/#isauthenticated

2022-03-03 21:48 UTC, diurnalist commented on trovi/settings.py
> +    "DEFAULT_AUTHENTICATION_CLASSES": [],
Should we put a default deny all on here, just in case?

2022-03-03 21:51 UTC, diurnalist commented on util/decorators.py
> +def timed_asynchronous_lru_cache(
ultra-nit-pick! this isn't asynchronous

2022-03-03 21:57 UTC, diurnalist commented
> We now make use of owner_urn fields to determine if a user has permission to perform certain operations on Artifacts. Right now, it only prevents modification of the owner_urn field. This work unfortunately has to be done in the serializer, to avoid having redundant parsing in a Permission class.

From my reading, this is not true in a lot of cases, at least from what I can see in this changeset.

2022-03-12 06:18 UTC, super-cooper reviewed
In order to save some time, I've pulled in the changes from the docs branch as well as the many fixes for bugs and issues we have discovered while migrating portal

2022-03-12 06:19 UTC, super-cooper commented
Here is the message from the initial docs commit, since it provides more context about those changes:

In conjunction with the new documentation endpoints, this patch
introduces a significant refactor which integrates many of the existing
classes more closely with Django REST Framework. The benefits of this
are twofold:

1. Less code complexity
2. Accurate documentation generation

Previously, a lot of behavior which exists natively in the Django REST
Framework was simply done manually, because it was easy enough to do.
Now, Trovi takes advantage of as many native Django REST Framework's
native faculties as possible.

The `ListArtifactsOrderingFilter` now understands the parameters used to
control it. It is also split into two separate filters in order to
optimize the order in which they are run: `ListArtifactsOrderingFilter`
and `ListArtifactsVisibilityFilter`. `ListArtifactsOrderingFilter` now
pre-annotates the query with attributes synonymous with the URL
parameters passed to the `ListArtifacts` endpoint. This allows the
filtering to be done with one super call.
`ListArtifactsVisibilityFilter` filters the queryset into only Artifacts
the user has permission to see. This includes public Artifacts,
Artifacts that have been shared with the user, and private Artifacts
which the user has authored. Unfortunately, the authorship lookup is
quite slow.

The `ListArtifactsPagination` class now produces an accurate OpenAPI
schema.

The `parsers` and schema modules are removed. With tighter integration
to Django REST Framework serializers, reliance on JSON Schema is
no longer needed. Regular JSON parsers suffice. All behavior previously
enforced by JSON Schema is now enforced by the serializer classes.

All serializers are updated to differentiate between read/write-only
fields, and nested objects are now represented via their own
serializers, even if they are not based on database models.
Docstrings have been refactored to be more accurate for documentation
generation.

The logic for `UpdateArtifact` still mostly remains in the
`ArtifactPatch` class, but now `UpdateArtifact` requests get their own
serializer, which creates the `ArtifactPatch`, and then performs a
partial update on an existing Artifact. `ArtifactPatch`'s `apply` method
has been refactored to perform partial updates via computing a shallow
diff between the old artifact and new Artifact generated by its supercall.
Since these requests are now validated by a serializer, they are now in
the form of a JSON object with a single field `"patch"`, rather than
just a bare list.

Due to the complicated nature of the Artifact views, their OpenAPI schema
has been manually extended using the `extend_schema_view` decorator, and
several `OpenApiSerializerExtension`s have been created to more
accurately describe some of our request/response data.

Finally, the new documentation endpoints are located under `docs/`. The
docs GUI is located at `docs/swagger` and the JSON Schema is located at
`docs/schema`.

Other changes:

* cityscape Made a slight change to token permissions to allow public access to
  resources without any required scopes
* sparkles Removed old owner_urn generator logic from the database layer
* card_index Added sorting database indexes for Artifacts
* heavy_plus_sign Take dependency on
  [`drf-spectacular`](https://drf-spectacular.readthedocs.io/en/latest/)
  for docs generation

2022-03-12 06:22 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Trovi 2.0: documentation site](https://trello.com/c/z537vXEe/2528-trovi-20-documentation-site)

2022-03-14 21:08 UTC, diurnalist requested changes
I saw one line where the authors were still being used to grant access to the artifact. This should not be the case and I already commented on it. Sometimes GitHub screws up the file view when there are multiple reviews, is it possible I was looking at an older version?

That should be fixed, everything else looks good I think.

2022-03-14 21:08 UTC, diurnalist commented on trovi/common/tokens.py
> +        return f"urn:{nid}:{nss}"
The URN format proposed in the arch doc is loose and didn't use the `urn:` prefix. If we use `urn:` I think really what we need is `urn:trovi:`. I would recommend dropping the urn: in front, I'm not sure it provides any value and not having it means we could start prefixing all our urns with the Trovi prefix on responses later, i.e., we can store "projects:chameleon:CHI-XXXXXX" and later can start returning that as `urn:trovi:projects:chameleon:CHI-XXXXXX`

2022-03-14 21:08 UTC, diurnalist commented on trovi/common/tokens.py
> +            # https://stackoverflow.com/a/10582820
Doesn't make sense and is a bit scary to me b/c I don't understand it. The only way I could understand it is if somehow dataclasses get wrapped up after they are evaluated. Yet, this seems to work:

```
>>> @dataclass(frozen=True)
... class MyClass:
...     @classmethod
...     def is_instance(cls, obj):
...         return isinstance(obj, MyClass)
...
>>> MyClass.is_instance(MyClass())
True
```

2022-03-14 21:08 UTC, diurnalist commented on trovi/common/tokens.py
> +            # https://stackoverflow.com/a/10582820
I'm reading that it could be a byproduct of module imports. It's too hard for me to see where this is imported, let's leave it as-is but this doesn't feel like something we necessarily have to work around.

2022-03-15 00:49 UTC, super-cooper reviewed
Changes inbound! I had a question about your URN comment but I believe I got to everything else.

2022-03-15 00:49 UTC, super-cooper commented on trovi/auth/serializers.py
> +        return trovi_token
Turns out, not so bad

2022-03-15 00:49 UTC, super-cooper commented on trovi/common/authenticators.py
> +        access_token = request.query_params.get("access_token")
Done

2022-03-15 00:49 UTC, super-cooper commented on trovi/common/authenticators.py
> +    def authenticate_header(self, _: Request) -> str:
Whoop. Pulled that example directly from the DRF docs

> Unauthenticated responses that are denied permission will result in an HTTP 401 Unauthorized response with an appropriate WWW-Authenticate header. For example:
>
> ```
> WWW-Authenticate: Token
> ```

2022-03-15 00:49 UTC, super-cooper commented on trovi/common/tokens.py
> +            # https://stackoverflow.com/a/10582820
So I've gone ahead and undone this. Before I believe there was a `from .` import which was the cause of the pain (since it was imported from within the package, which hadn't finished initializing yet). This could come up again in the future, but for now it's working fine.

2022-03-15 00:49 UTC, super-cooper commented on trovi/common/tokens.py
> +        return f"urn:{nid}:{nss}"
Are you saying that URNs shown to users have `urn:trovi`, but internally, we don't store any of that? And do you mean this for all the URNs we use? This would also mean we have to translate URNs from incoming requests to lop the `urn:trovi` part off

2022-03-15 00:49 UTC, super-cooper commented on trovi/models.py
> +post_save.connect(ArtifactEvent.incr_access_count, sender=ArtifactEvent)
Good catch! I have put it inside the function itself.

2022-03-15 00:49 UTC, super-cooper commented on trovi/models.py
> +post_delete.connect(ArtifactVersion.delete_access_count, sender=ArtifactVersion)
;) I was happy with myself for realizing this would be easier and faster to do on the version rather than the event, especially because we don't delete events except on `CASCADE`.

2022-03-15 00:49 UTC, super-cooper commented on trovi/storage/serializers.py
> +                        f"?temp_url_sig={hmac.new(bytes([random.randint(0, 10)]), bytes([random.randint(0, 10)]), hashlib.sha1).hexdigest()}"
I just copy pasted from the swift integration :)

2022-03-15 00:49 UTC, super-cooper commented on util/decorators.py
> +def timed_asynchronous_lru_cache(
well,

2022-03-15 00:51 UTC, super-cooper commented
I also added the correct token error response according to that RFC.

2022-03-15 01:26 UTC, diurnalist approved these changes
Thanks for the quick turnaround! Think this is 🥇 now

2022-03-15 01:26 UTC, diurnalist commented on trovi/common/tokens.py
> +        return f"urn:{nid}:{nss}"
I'm saying, let's leave off `urn:` for now. We can always add it in later. If we persist the value w/o that prefix it's easy to add it on the responses, and yes, we could lop it off on the request end before storing.

2022-03-15 18:15 UTC, merged