Add git backend
ChameleonCloud/trovi pull request #36
Opened 2022-04-26 15:24 UTC by Mark-Powers

2022-04-26 19:07 UTC, super-cooper requested changes
Looks great; very clean! I pointed out a couple things, and also have some questions about the scope of this part of Trovi, since I was not in the meeting with you and Jason. 

I also ran black format on the files as I looked at them, since I have it bound to a keyboard macro. Will be pushing a commit with those reformats.

2022-04-26 19:07 UTC, super-cooper commented on trovi/urn.py
> +def parse_project_urn(project_urn):
This is much better than what I had before. I would prefer that this file be in `util`, and that these functions have type annotations to be consistent with the rest of the codebase.

2022-04-26 19:27 UTC, Mark-Powers commented on trovi/storage/backends/git.py
> +        exp = int(
good idea

2022-04-26 19:27 UTC, Mark-Powers commented on trovi/urn.py
> +def parse_project_urn(project_urn):
Moved

2022-04-26 19:27 UTC, Mark-Powers commented on trovi/storage/backends/__init__.py
> +        return GitBackend(name, content_type, content_id)
I don't think it is? It seems to be working fine, but I've updated this since it doesn't hurt.

2022-04-26 19:30 UTC, Mark-Powers commented on trovi/storage/backends/git.py
> +        if "github.com" not in self.remote_url or not self.remote_url.startswith("http"):
I agree urlparse is better. The ssh clone url github gives me does not parse with the default urlparse. I know github does not allow anonymous ssh access, even for clone. So we should encourage users to use http instead anyway. 

I'll see about adding it for gitlab as well.

2022-04-26 19:32 UTC, super-cooper commented on trovi/storage/backends/git.py
> +        if "github.com" not in self.remote_url or not self.remote_url.startswith("http"):
Ahhh, good call on SSH. In that case, maybe we should reject SSH URLs.

2022-04-26 21:46 UTC, Mark-Powers commented
This now adds a giturlparse library which is a bit better at parsing git urls. It theoretically can rewrite ssh proto into https, but I couldn't get it to work, it seems like there are some serious bugs in the library regarding this.

2022-04-27 16:02 UTC, super-cooper approved these changes
Looks great!

2022-04-27 16:05 UTC, Mark-Powers commented on trovi/storage/backends/git.py
> +            url = f"https://gitlab.com/{self.parsed_git_url.owner}/{self.parsed_git_url.repo}/-/archive/{self.ref}/{self.parsed_git_url.repo}-{self.ref}.zip"
It should only be a hash, so I think this code should be fine.

2022-04-27 16:07 UTC, Mark-Powers commented on trovi/storage/backends/git.py
> +        if getattr(parse_result, "protocol", None) != "https":
Good point, I thought maybe we needed https to craft the URL, but that is not the case anymore.

2022-04-27 16:16 UTC, diurnalist approved these changes
LGTM!

2022-04-27 16:16 UTC, diurnalist commented on pyproject.toml
> +giturlparse = "^0.10.0"
👍🏻 - no dependencies, code looks reasonable, small tight library, about what I would expect for a collection of regexes with some nice accessors :)

2022-04-27 16:16 UTC, diurnalist commented on trovi/storage/backends/git.py
> +        return HttpDownloadLink(
good use of a higher-level data structure here 👍🏻 (general comment, I missed this on earlier PRs)

2022-04-27 16:16 UTC, diurnalist commented on trovi/storage/backends/tests.py
> +        self.assertEqual(actual, expected)
Nice tests!

2022-04-27 16:16 UTC, diurnalist commented on trovi/storage/links/git.py
> +    ref: str
I'm actually surprised this is valid, it defaults to None? Haven't seen definitions w/o a declaration like this before

2022-04-28 14:08 UTC, merged