add unique access count metric and metric at artifact level
ChameleonCloud/trovi pull request #66
Opened 2022-09-12 14:25 UTC by zhenz

2022-09-12 18:36 UTC, super-cooper requested changes
I like how small the footprint of this change is :) I was worried that it was going to be difficult to fit it in. I have a suggestion for optimization, and to expose the new field to the docs generator.

Also, could you write a simple unit test for this? I think it could be almost exactly the same as the one for [`access_count`](https://github.com/ChameleonCloud/trovi/blob/cc3dd3045c7a65c65a3af9261fdcd3c73c5b42f1/trovi/api/tests.py#L973).

2022-09-12 18:36 UTC, super-cooper commented on trovi/api/serializers.py
> +        }
`Artifact`s already have an `access_count` field which we can use here. I also checked, and I think it's possible to limit the calculation of `unique_access_count` to a single SQL query, similar to how you did it for `ArtifactVersion`

```suggestion
        return {
            "access_count": total_access_count,
            "unique_access_count": ArtifactEvent.objects.filter(
                artifact_version__artifact=instance,
                event_type=ArtifactEvent.EventType.LAUNCH,
            )
            .values("event_origin")
            .distinct()
            .count(),
        }
```

2022-09-25 19:26 UTC, zhenz commented
> I like how small the footprint of this change is :) I was worried that it was going to be difficult to fit it in. I have a suggestion for optimization, and to expose the new field to the docs generator.
> 
> Also, could you write a simple unit test for this? I think it could be almost exactly the same as the one for [`access_count`](https://github.com/ChameleonCloud/trovi/blob/cc3dd3045c7a65c65a3af9261fdcd3c73c5b42f1/trovi/api/tests.py#L973).

@super-cooper Thanks! and sorry for taking so long to address your comments. Those are great suggestions!

2022-09-26 18:14 UTC, super-cooper approved these changes
Looks great!

2022-09-26 20:21 UTC, merged