add unique cell execution count metric
ChameleonCloud/trovi pull request #72
Opened 2022-09-26 18:14 UTC by zhenz

2022-09-26 18:17 UTC, Mark-Powers approved these changes
Looks good to me!

2022-09-26 22:37 UTC, super-cooper requested changes
Looks good! I have one change I'd like to see in the serializer.

2022-09-27 16:42 UTC, super-cooper approved these changes
The original solution LGTM. I pushed some commits to bring it back.

2022-09-27 16:42 UTC, super-cooper commented on trovi/api/serializers.py
> +    event_type = serializers.CharField(allow_null=False, required=False)
I think I may have screwed this up. It looks like users are not able to specify multiple metrics anyway. I think your original solution was the correct one. 

Since you force-pushed, the old code is not in version control anymore, but I was able to find it in my editor's local history. Very sorry for asking you to do an unnecessary fix.

I also went ahead and moved the create_event and logic into the update function, since I thought the execution flow was a little clearer.

2022-09-27 19:32 UTC, merged